name: gcc_currency
description: GCC currency symbols as Flutter icons and text
version: 0.0.1
homepage: https://github.com/fathah/gcc_currency

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: GCCCurrency
      fonts:
        - asset: assets/fonts/gcc_currency.ttf
